trigger:
- '*'

pool:
  vmImage: 'ubuntu-20.04'
  demands:
  - maven

variables:
  env1: 'sit'
  sec: 'fly'

steps:
- script: 'echo "Run some random shell commands"'
  displayName: 'Shell commands'

# Maven
# Build, test, and deploy with Apache Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml' 
    goals: 'package' # Optional
    publishJUnitResults: true 
    testResultsFiles: '**/surefire-reports/TEST-*.xml' # Required when publishJUnitResults == True
    codeCoverageToolOption: 'jaCoCo' # Optional. Options: none, cobertura, jaCoCo. Enabling code coverage inserts the `clean` goal into the Maven goals list when Maven runs.
  
#Copy files to target folder
- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'    

- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    artifactName: 'helloWorldJava'